### ISSUE TITLE
A serious question about eaglercraft 1.8.8 and multiplayer. Please read

### ISSUE THREAD

**Issue by HedgyhogGuy** [lax1dude/origin-blacklist-1.8#1]
I'm playing on Eaglercraft using the html file. My chromebook can't run js files or anything else, so I'm stuck with this version. I'm fine with that, there's just one issue: multiplayer doesn't work. I've tried everything I can, it just isn't working. my Chromebook got unblocked for a day, and I played an online version of Eagler, and it worked. It's the same with 1.5.2 also. I hope you can help me. Please don't ignore this post.

**Comment by lax1dude** [comment]
your chromebook's admin most likely blocked the relay servers required for two clients to discover each other and/or communicate, there's nothing you can do about this

**Comment by HedgyhogGuy** [comment]
so if that's true, why did the web version work with multiplayer?

**Comment by HedgyhogGuy** [comment]
also that doesn't explain how my brother could do it and I'm pretty sure on of my friends too
